'use client';

import React from 'react';
import { Section } from '@/components/ui/Section';

export default function TermsOfServicePage() {
  return (
    <Section variant="primary" style={{ paddingTop: '12rem', paddingBottom: '8rem', ...({} as any) }}>
      <div style={{ maxWidth: '800px', marginInline: 'auto', ...({} as any) }}>
        <h4 className="technical-text" style={{ color: 'var(--accent-primary)', marginBottom: '1.5rem', letterSpacing: '0.2rem' }}>
          REGULATORY DOCUMENT / v1.1 HARDENED
        </h4>
        <h1 style={{ fontSize: '3.5rem', marginBottom: '1rem', letterSpacing: '-0.04em' }}>Terms of Service</h1>
        <div style={{ display: 'flex', gap: '2rem', marginBottom: '4rem', fontSize: '0.8rem', opacity: 0.5 }} className="technical-text">
          <span>LAST UPDATED: 2026-03-23</span>
          <span>VERSION: v1.1 HARDENED</span>
        </div>
        
        <div className="legal-content" style={{ display: 'flex', flexDirection: 'column', gap: '3rem', fontSize: '1.1rem', lineHeight: 1.7, color: 'var(--text-secondary)' }}>
          
          <section>
            <h3 style={{ color: 'var(--text-primary)', marginBottom: '1rem', fontSize: '1.4rem' }}>1. The Platform Role</h3>
            <p>
              Print Price Pro ("the Platform") is a production intelligence and matchmaking system operated by Print Price Pro SIA. The Platform provides pricing estimation, file validation (preflight), and manufacturing routing services.
            </p>
            <p style={{ marginTop: '1rem', color: 'var(--accent-primary)', fontWeight: 700 }}>
              IMPORTANT: Print Price Pro is NOT a printing company, manufacturer, or seller of physical goods. We do not own, operate, or control the printing facilities mentioned in our results.
            </p>
          </section>

          <section>
            <h3 style={{ color: 'var(--text-primary)', marginBottom: '1rem', fontSize: '1.4rem' }}>2. Intermediary Relationship</h3>
            <p>
              The Platform acts solely as a technical intermediary. Any production contract, purchase order, or agreement for the manufacture of goods is strictly between the User and the third-party Printer. Print Price Pro is not a party to these contracts and assumes no liability for their performance.
            </p>
          </section>

          <section>
            <h3 style={{ color: 'var(--text-primary)', marginBottom: '1rem', fontSize: '1.4rem' }}>3. Pricing & Estimates</h3>
            <p>
              All prices, lead times, and specifications generated by the Platform are <strong>INDICATIVE ONLY</strong>. They do not constitute a binding offer from Print Price Pro or the Printer. Final pricing is subject to the Printer’s direct confirmation and may vary based on file complexity, material availability, and production capacity.
            </p>
          </section>

          <section>
            <h3 style={{ color: 'var(--text-primary)', marginBottom: '1rem', fontSize: '1.4rem' }}>4. AI & Automated Decision Tools</h3>
            <p>
              The Platform utilizes automated algorithms and AI to validate production files and optimize manufacturing routing. While we strive for high technical accuracy, we do not guarantee the error-free nature of these automated processes.
            </p>
          </section>

          <section>
            <h3 style={{ color: 'var(--text-primary)', marginBottom: '1rem', fontSize: '1.4rem' }}>5. User Responsibility</h3>
            <p>
              Users are solely responsible for the technical integrity and legal compliance of the files they upload. The Platform's "Preflight" check is an advisory tool and does not relieve the User of their obligation to ensure files meet production standards.
            </p>
          </section>

          <section>
            <h3 style={{ color: 'var(--text-primary)', marginBottom: '1rem', fontSize: '1.4rem' }}>6. Limitation of Liability</h3>
            <p>
              To the maximum extent permitted by Latvian law, Print Price Pro SIA shall not be liable for:
            </p>
            <ul style={{ paddingLeft: '1.5rem', marginTop: '1rem' }}>
              <li>Production defects, delays, or failures caused by third-party printers.</li>
              <li>Financial losses arising from indicative pricing variations.</li>
              <li>System downtime or data loss.</li>
              <li>Errors in automated file validation.</li>
            </ul>
          </section>

          <section>
            <h3 style={{ color: 'var(--text-primary)', marginBottom: '1rem', fontSize: '1.4rem' }}>7. Governing Law</h3>
            <p>
              These terms are governed by the laws of the Republic of Latvia. Any disputes shall be subject to the exclusive jurisdiction of the courts of Riga, Latvia.
            </p>
          </section>

          {/* v1.1 PH HARDENING ADDITIONS */}

          <section>
            <h3 style={{ color: 'var(--text-primary)', marginBottom: '1rem', fontSize: '1.4rem' }}>8. Data Sharing with Printers</h3>
            <p>
              By using the Platform, the User expressly authorizes Print Price Pro to share project specifications, files, and relevant data with selected third-party Printers for the purpose of quotation, production evaluation, and fulfillment. 
            </p>
            <p>
              Print Price Pro is not responsible for how Printers process such data beyond the scope of this professional purpose.
            </p>
          </section>

          <section>
            <h3 style={{ color: 'var(--text-primary)', marginBottom: '1rem', fontSize: '1.4rem' }}>9. Intellectual Property & Content Rights</h3>
            <p>
              The User retains full ownership of all submitted files and content. By uploading content, the User grants Print Price Pro and its partner Printers a limited, non-exclusive license to process and use the files solely for the purpose of providing the service. 
            </p>
            <p>
              The User warrants that they have all necessary rights to the content submitted and that it does not infringe upon any third-party intellectual property or violate any applicable laws.
            </p>
          </section>

          <section>
            <h3 style={{ color: 'var(--text-primary)', marginBottom: '1rem', fontSize: '1.4rem' }}>10. Service Availability</h3>
            <p>
              The Platform is provided on an "as is" and "as available" basis. We do not guarantee uninterrupted or error-free operation and may suspend, modify, or discontinue the service at any time without prior notice for maintenance, updates, or strategic realignment.
            </p>
          </section>

          <section>
            <h3 style={{ color: 'var(--text-primary)', marginBottom: '1rem', fontSize: '1.4rem' }}>11. Data Processing</h3>
            <p>
              User data is processed in accordance with our <strong>Privacy Policy</strong>. The Platform may collect behavioral and technical data (including interaction events, usage patterns, and decision latency) for system optimization, market signal analysis, and performance improvement.
            </p>
          </section>

          <section>
            <h3 style={{ color: 'var(--text-primary)', marginBottom: '1rem', fontSize: '1.4rem' }}>12. Payments</h3>
            <p>
              Where applicable, payments for production services may be processed either via the Platform or directly by the Printer. Print Price Pro is not responsible for payment processing errors, currency fluctuations, or third-party payment provider issues.
            </p>
          </section>

          <section>
            <h3 style={{ color: 'var(--text-primary)', marginBottom: '1rem', fontSize: '1.4rem' }}>13. Force Majeure</h3>
            <p>
              Print Price Pro shall not be liable for any failure or delay in performance caused by events beyond its reasonable control, including but not limited to supply chain disruptions, technical failures, labor disputes, acts of nature, or global infrastructure outages.
            </p>
          </section>

        </div>

        <div style={{ marginTop: '8rem', borderTop: '1px solid rgba(255,255,255,0.1)', paddingTop: '2rem' }}>
          <p className="technical-text" style={{ fontSize: '0.8rem', opacity: 0.5 }}>
            PRINT PRICE PRO / DOCUMENT AUTHENTICITY SECURED // HARDENED v1.1 // 2026-03-23
          </p>
        </div>
      </div>
    </Section>
  );
}
